version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - mynet
    restart: always
    
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception42
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - mynet
    depends_on:
      - mariadb
    # command: ["bash", "/var/www/wordpress/config.sh"]
    restart: always

volumes:
  wordpress:
    driver: local
  mariadb:
    driver: local

networks:
  mynet:
    driver: bridge
