
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - mynet
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception42
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - mynet
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always


  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception42
    env_file:
      - .env  
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
     - mynet 
    restart: always


volumes:
  wordpress: 
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/nbouhali/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/nbouhali/data/mariadb
networks:
  mynet:
    driver: bridge
